wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.9
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.15
    start_time: 1718019763.281533
    t:
      1:
      - 55
      2:
      - 55
      3:
      - 16
      - 23
      4: 3.9.15
      5: 0.13.9
      8:
      - 5
path:
  desc: null
  value: wandb_test
